[package]
name = "hello_rowan"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rowan = "0.10.0"
m_lexer = "0.0.4"
